import { validateBlueprint } from "./src/ai/validators/blueprint.validator.js";


// The Blueprint generated by your Meta Architect
const blueprint = {
    metadata: {
        id: 'manali_trip_planning',
        version: '1.0.0',
        generatedFrom: 'Intent Object',
        complexity: 'MEDIUM'
    },
    execution: {
        entryTask: 'research_manali',
        allowParallel: false,
        allowLoops: false,
        maxRetries: 3,
        maxTasks: 7
    },
    tasks: [
        {
            id: 'research_manali',
            name: 'Research Manali Travel',
            objective: 'Gather information on traveling to Manali',
            rationale: 'Understanding travel options, costs, and activities in Manali',
            requiredTools: ['web_search_tool'],
            dependencies: [],
            expectedInput: [],
            expectedOutput: ['travel_options', 'costs', 'activities'],
            successCriteria: ['information gathered']
        },
        {
            id: 'plan_transportation',
            name: 'Plan Transportation',
            objective: 'Determine the best transportation options within the budget',
            rationale: 'Finding affordable and efficient ways to travel around Manali',
            requiredTools: [],
            dependencies: ['research_manali'],
            expectedInput: ['travel_options', 'costs'],
            expectedOutput: ['transportation_plan'],
            successCriteria: ['transportation plan finalized']
        },
        {
            id: 'book_accommodation',
            name: 'Book Accommodation',
            objective: 'Find and book affordable accommodation',
            rationale: 'Securing a place to stay within the budget',
            requiredTools: ['web_search_tool'],
            dependencies: ['plan_transportation'],
            expectedInput: ['accommodation_options', 'budget'],
            expectedOutput: ['accommodation_booking'],
            successCriteria: ['accommodation booked']
        },
        {
            id: 'plan_activities',
            name: 'Plan Activities',
            objective: 'Determine the best activities and sightseeing options',
            rationale: 'Creating a fun and engaging itinerary',
            requiredTools: [],
            dependencies: ['book_accommodation'],
            expectedInput: ['activities', 'time_available'],
            expectedOutput: ['activity_plan'],
            successCriteria: ['activity plan finalized']
        },
        {
            id: 'create_itinerary',
            name: 'Create Itinerary',
            objective: 'Compile all plans into a detailed 5-day itinerary',
            rationale: 'Finalizing a comprehensive plan for the trip',
            requiredTools: [],
            dependencies: ['plan_activities'],
            expectedInput: [
                'transportation_plan',
                'accommodation_booking',
                'activity_plan'
            ],
            expectedOutput: ['detailed_itinerary'],
            successCriteria: ['itinerary created']
        },
        {
            id: 'budget_check',
            name: 'Check Budget',
            objective: 'Ensure the itinerary fits within the 10,000 INR budget',
            rationale: 'Verifying that all plans are within budget',
            requiredTools: [],
            dependencies: ['create_itinerary'],
            expectedInput: ['detailed_itinerary', 'budget'],
            expectedOutput: ['budget_confirmation'],
            successCriteria: ['budget confirmed']
        }
    ],
    edges: [
        { from: 'START', to: 'research_manali', condition: 'ALWAYS' },
        {
            from: 'research_manali',
            to: 'plan_transportation',
            condition: 'SUCCESS'
        },
        {
            from: 'plan_transportation',
            to: 'book_accommodation',
            condition: 'SUCCESS'
        },
        {
            from: 'book_accommodation',
            to: 'plan_activities',
            condition: 'SUCCESS'
        },
        {
            from: 'plan_activities',
            to: 'create_itinerary',
            condition: 'SUCCESS'
        },
        {
            from: 'create_itinerary',
            to: 'budget_check',
            condition: 'SUCCESS'
        },
        { from: 'budget_check', to: 'END', condition: 'SUCCESS' }
    ],
    constraints: {
        requiresVerification: true,
        allowParallel: false,
        requiresHumanApproval: false
    },
    successCriteria: [
        'Research completed',
        'Transportation plan finalized',
        'Accommodation booked',
        'Activities planned',
        'Itinerary compiled',
        'Budget confirmed',
        'Final itinerary delivered'
    ],
    finalOutput: {
        artifact: '5‑day detailed travel itinerary for Manali within a 10,000 INR budget',
        format: 'JSON document containing day‑by‑day schedule, transportation details, accommodation info, activity list, and cost breakdown'
    }
}

// Execute Validation
const runTest = () => {
    console.log(`[🚀] Starting validation for Blueprint: ${blueprint.metadata.id}...\n`);

    const startTime = performance.now();
    const result = validateBlueprint(blueprint);
    const endTime = performance.now();

    // Strip the full blueprint payload from the terminal output to keep it clean
    const { blueprint: _, ...cleanResult } = result;

    if (result.valid) {
        console.log(`[✅] Validation Passed in ${(endTime - startTime).toFixed(2)}ms`);
        console.log("\n--- Metrics ---");
        console.log(JSON.stringify(cleanResult.metrics, null, 2));
    } else {
        console.log(`[❌] Validation Failed in ${(endTime - startTime).toFixed(2)}ms`);
    }

    if (cleanResult.errors.length > 0) {
        console.log("\n--- Errors ---");
        console.log(JSON.stringify(cleanResult.errors, null, 2));
    }

    if (cleanResult.warnings.length > 0) {
        console.log("\n--- Warnings ---");
        console.log(JSON.stringify(cleanResult.warnings, null, 2));
    }
};

runTest();