import { qwen27b } from "../models/qwen27b.js";
import { logger } from "../../utils/logger.js";
import { retryWithRateLimit } from "../../utils/retryWithRateLimit.js";

export const responseGeneratorNode = async (state, config) => {
    logger.info("📝 Response Generator: Converting final output to Markdown...");

    const prompt = `You are an expert AI assistant designed to format system outputs into beautiful, human-readable Markdown.
The system has just completed a complex workflow to fulfill the user's request.
Below is the raw JSON output generated by the backend runtime agents.

Your task is to present this data to the user in a highly polished, conversational Markdown format.
- DO NOT output raw JSON.
- Synthesize the JSON data into a natural, helpful, and professional response.
- Use formatting such as headings (##), bold text, bullet points, and proper code blocks (with syntax highlighting) where appropriate.

RAW SYSTEM DATA:
${JSON.stringify(state.finalOutput, null, 2)}
`;

    const response = await retryWithRateLimit(() => 
        qwen27b.invoke([
            {
                role: "system",
                content: prompt
            },
            {
                role: "user",
                content: state.userQuery
            }
        ]),
        config
    );

    return {
        finalMarkdown: response.content
    };
};
